# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7Uold_tuaClbL-FPAWU17GN9X1qnT-q
"""

# ============================================================
# CELL 1 - ENVIRONMENT SETUP & SPARK SESSION
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import DoubleType, IntegerType

# Khởi tạo SparkSession tối ưu bộ nhớ cho Colab
spark = SparkSession.builder \
    .appName("Amazon_Delivery_Time_Prediction") \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

print("⚡ PySpark Session khởi tạo thành công!")
print(f"Phiên bản PySpark: {spark.version}")

# Tải file amazon_delivery.csv trực tiếp từ Colab
from google.colab import files
print("\n👉 Vui lòng tải file 'amazon_delivery.csv' lên Colab:")
uploaded = files.upload()

# ============================================================
# CELL 2 - DATA LOADING & CLEANING
# ============================================================
# 1. Đọc dữ liệu CSV bằng PySpark
file_path = list(uploaded.keys())[0] if uploaded else "amazon_delivery.csv"
df = spark.read.csv(file_path, header=True, inferSchema=True)

# 2. Chuẩn hóa tên cột (loại bỏ khoảng trắng)
for col in df.columns:
    df = df.withColumnRenamed(col, col.strip())

# 3. Ép kiểu dữ liệu các cột quan trọng (nếu bị đọc nhầm dạng string)
numeric_candidates = ["Delivery_Time", "Agent_Age", "Agent_Rating", "Distance"]
for col_name in numeric_candidates:
    if col_name in df.columns:
        df = df.withColumn(col_name, F.col(col_name).cast(DoubleType()))

# 4. Loại bỏ giá trị Null / Missing
df = df.dropna()

print(f"Tổng số bản ghi sau khi làm sạch: {df.count()} dòng")
df.printSchema()
df.show(5)

# ============================================================
# CELL 3 - EXPLORATORY DATA ANALYSIS (EDA)
# ============================================================
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11})

# Chuyển dữ liệu Spark sang Pandas cho Matplotlib/Seaborn
pdf = df.toPandas()

# ------------------------------------------------------------
# 1. Phân phối thời gian giao hàng (Delivery Time)
# ------------------------------------------------------------
plt.figure(figsize=(10, 5))
sns.histplot(pdf["Delivery_Time"], kde=True, color="teal", bins=30)
plt.title("1. Distribution of Delivery Time", fontsize=14, fontweight='bold')
plt.xlabel("Delivery Time (minutes)")
plt.ylabel("Number of Orders")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 2. Ma trận tương quan (Correlation Heatmap)
# ------------------------------------------------------------
numeric_cols = pdf.select_dtypes(include=np.number).columns
plt.figure(figsize=(10, 7))
sns.heatmap(pdf[numeric_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm", vmin=-1, vmax=1)
plt.title("2. Correlation Matrix of Numeric Features", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 3. Thời gian giao hàng trung bình theo Tình trạng Giao thông (Traffic)
# ------------------------------------------------------------
if "Traffic" in df.columns:
    traffic_df = df.groupBy("Traffic").agg(
        F.count("*").alias("Orders"),
        F.avg("Delivery_Time").alias("Avg_Delivery_Time")
    ).orderBy(F.desc("Avg_Delivery_Time")).toPandas()

    plt.figure(figsize=(8, 5))
    sns.barplot(data=traffic_df, x="Traffic", y="Avg_Delivery_Time", palette="Reds_r")
    plt.title("3. Average Delivery Time by Traffic Condition", fontsize=14, fontweight='bold')
    plt.xlabel("Traffic Condition")
    plt.ylabel("Average Delivery Time (mins)")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 4. Thời gian giao hàng trung bình theo Thời tiết (Weather)
# ------------------------------------------------------------
if "Weather" in df.columns:
    weather_df = df.groupBy("Weather").agg(
        F.count("*").alias("Orders"),
        F.avg("Delivery_Time").alias("Avg_Delivery_Time")
    ).orderBy(F.desc("Avg_Delivery_Time")).toPandas()

    plt.figure(figsize=(10, 5))
    sns.barplot(data=weather_df, x="Weather", y="Avg_Delivery_Time", palette="Blues_r")
    plt.title("4. Average Delivery Time by Weather", fontsize=14, fontweight='bold')
    plt.xlabel("Weather Condition")
    plt.ylabel("Average Delivery Time (mins)")
    plt.xticks(rotation=30)
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 5. Phân bố số lượng đơn hàng theo Khu vực (Area)
# ------------------------------------------------------------
if "Area" in df.columns:
    area_df = df.groupBy("Area").count().orderBy(F.desc("count")).toPandas()

    plt.figure(figsize=(8, 5))
    sns.barplot(data=area_df, x="Area", y="count", palette="Greens_r")
    plt.title("5. Total Number of Deliveries by Area", fontsize=14, fontweight='bold')
    plt.xlabel("Area Type")
    plt.ylabel("Number of Orders")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 6. Thời gian giao hàng trung bình theo Phương tiện (Vehicle)
# ------------------------------------------------------------
if "Vehicle" in df.columns:
    vehicle_df = df.groupBy("Vehicle").agg(
        F.avg("Delivery_Time").alias("Avg_Delivery_Time")
    ).orderBy(F.desc("Avg_Delivery_Time")).toPandas()

    plt.figure(figsize=(8, 5))
    sns.barplot(data=vehicle_df, x="Vehicle", y="Avg_Delivery_Time", palette="Purples_r")
    plt.title("6. Average Delivery Time by Vehicle Type", fontsize=14, fontweight='bold')
    plt.xlabel("Vehicle")
    plt.ylabel("Average Delivery Time (mins)")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 7. Boxplot thời gian giao hàng theo Tình trạng Giao thông (Traffic)
# ------------------------------------------------------------
if "Traffic" in pdf.columns:
    plt.figure(figsize=(9, 5))
    sns.boxplot(data=pdf, x="Traffic", y="Delivery_Time", palette="Set2")
    plt.title("7. Delivery Time Distribution & Outliers by Traffic", fontsize=14, fontweight='bold')
    plt.xlabel("Traffic")
    plt.ylabel("Delivery Time (mins)")
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 8. Boxplot thời gian giao hàng theo Thời tiết (Weather)
# ------------------------------------------------------------
if "Weather" in pdf.columns:
    plt.figure(figsize=(11, 5))
    sns.boxplot(data=pdf, x="Weather", y="Delivery_Time", palette="Set3")
    plt.title("8. Delivery Time Distribution & Outliers by Weather", fontsize=14, fontweight='bold')
    plt.xlabel("Weather")
    plt.ylabel("Delivery Time (mins)")
    plt.xticks(rotation=25)
    plt.tight_layout()
    plt.show()

# ------------------------------------------------------------
# 9. Tương quan giữa Đánh giá Shiper (Agent_Rating) và Delivery Time
# ------------------------------------------------------------
if "Agent_Rating" in pdf.columns:
    plt.figure(figsize=(9, 5))
    sns.scatterplot(data=pdf, x="Agent_Rating", y="Delivery_Time", alpha=0.5, color="darkorange")
    plt.title("9. Agent Rating vs. Delivery Time", fontsize=14, fontweight='bold')
    plt.xlabel("Agent Rating")
    plt.ylabel("Delivery Time (mins)")
    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 4 - FEATURE ENGINEERING & PIPELINE
# ============================================================
from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, OneHotEncoder, VectorAssembler

# Xác định danh sách biến phân loại (Categorical) và biến định lượng (Numerical)
categorical_cols = [c for c in ["Weather", "Traffic", "Vehicle", "Area", "Category"] if c in df.columns]
numerical_cols = [c for c in ["Agent_Age", "Agent_Rating", "Distance"] if c in df.columns]

stages = []

# 1. Mã hóa các biến danh mục (StringIndexer -> OneHotEncoder)
indexed_cols = [f"{c}_index" for c in categorical_cols]
encoded_cols = [f"{c}_vec" for c in categorical_cols]

indexer = StringIndexer(inputCols=categorical_cols, outputCols=indexed_cols, handleInvalid="keep")
encoder = OneHotEncoder(inputCols=indexed_cols, outputCols=encoded_cols)

stages += [indexer, encoder]

# 2. Gom tất cả đặc trưng vào 1 Vector duy nhất bằng VectorAssembler
assembler_inputs = encoded_cols + numerical_cols
assembler = VectorAssembler(inputCols=assembler_inputs, outputCol="features")
stages.append(assembler)

# 3. Khởi tạo Pipeline
pipeline = Pipeline(stages=stages)
pipeline_model = pipeline.fit(df)
prepared_df = pipeline_model.transform(df)

# Chia tập dữ liệu Train (80%) và Test (20%)
train_data, test_data = prepared_df.randomSplit([0.8, 0.2], seed=42)

print(f"Dữ liệu huấn luyện (Train): {train_data.count()} mẫu")
print(f"Dữ liệu kiểm thử (Test): {test_data.count()} mẫu")

# ============================================================
# CELL 5 - MODEL TRAINING & EVALUATION
# ============================================================
from pyspark.ml.regression import LinearRegression, RandomForestRegressor, GBTRegressor
from pyspark.ml.evaluation import RegressionEvaluator

# Khởi tạo các mô hình
models = {
    "Linear Regression": LinearRegression(featuresCol="features", labelCol="Delivery_Time"),
    "Random Forest": RandomForestRegressor(featuresCol="features", labelCol="Delivery_Time", numTrees=50, seed=42),
    "Gradient-Boosted Trees": GBTRegressor(featuresCol="features", labelCol="Delivery_Time", maxIter=30, seed=42)
}

evaluator_rmse = RegressionEvaluator(labelCol="Delivery_Time", predictionCol="prediction", metricName="rmse")
evaluator_r2 = RegressionEvaluator(labelCol="Delivery_Time", predictionCol="prediction", metricName="r2")
evaluator_mae = RegressionEvaluator(labelCol="Delivery_Time", predictionCol="prediction", metricName="mae")

results = []

print("🚀 Đang tiến hành huấn luyện và đánh giá các mô hình...\n")

for name, model in models.items():
    # Fit mô hình
    trained_model = model.fit(train_data)
    predictions = trained_model.transform(test_data)

    # Tính các chỉ số
    rmse = evaluator_rmse.evaluate(predictions)
    r2 = evaluator_r2.evaluate(predictions)
    mae = evaluator_mae.evaluate(predictions)

    results.append({"Model": name, "RMSE": rmse, "R2 Score": r2, "MAE": mae})

# Hiển thị bảng so sánh kết quả
results_df = pd.DataFrame(results)
print("="*50)
print("📊 BẢNG SO SÁNH KẾT QUẢ MÔ HÌNH")
print("="*50)
print(results_df.to_string(index=False))

# Biểu đồ so sánh RMSE giữa các mô hình
plt.figure(figsize=(8, 4))
sns.barplot(data=results_df, x="Model", y="RMSE", palette="viridis")
plt.title("Model Comparison - Root Mean Squared Error (RMSE)", fontsize=13, fontweight='bold')
plt.ylabel("RMSE (Thấp hơn là tốt hơn)")
plt.tight_layout()
plt.show()

# ============================================================
# CELL 6 - FEATURE IMPORTANCE & PREDICTION VISUALIZATION (FIXED)
# ============================================================
# 1. Huấn luyện Random Forest để trích xuất Feature Importance
rf = RandomForestRegressor(featuresCol="features", labelCol="Delivery_Time", numTrees=50, seed=42)
rf_model = rf.fit(train_data)

# 2. Trích xuất mảng tầm quan trọng của đặc trưng
importances = rf_model.featureImportances.toArray()

# 3. Tự động lấy tên chính xác của các cột (bao gồm cả các cột đã qua OneHotEncoder)
try:
    attrs = train_data.schema["features"].metadata["ml_attr"]["attrs"]
    feature_list = []
    for key in ["numeric", "binary", "nominal"]:
        if key in attrs:
            for item in attrs[key]:
                feature_list.append((item["idx"], item["name"]))
    feature_list.sort(key=lambda x: x[0])
    feature_names = [x[1] for x in feature_list]
except Exception:
    feature_names = [f"Feature_{i}" for i in range(len(importances))]

# Đảm bảo khớp độ dài tuyệt đối trước khi đưa vào DataFrame
if len(feature_names) != len(importances):
    feature_names = [f"Feature_{i}" for i in range(len(importances))]

# 4. Tạo DataFrame & Trực quan hóa Feature Importance
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
# Hiển thị Top 15 đặc trưng quan trọng nhất
sns.barplot(data=feature_importance_df.head(15), x='Importance', y='Feature', palette='magma')
plt.title("Top Feature Importance Analysis (Random Forest)", fontsize=14, fontweight='bold')
plt.xlabel("Importance Score")
plt.tight_layout()
plt.show()

# 5. Trực quan hóa kết quả dự báo Thực tế vs Dự đoán
predictions = rf_model.transform(test_data)
pred_pd = predictions.select("Delivery_Time", "prediction").limit(200).toPandas()

plt.figure(figsize=(9, 5))
sns.scatterplot(data=pred_pd, x="Delivery_Time", y="prediction", alpha=0.7, color="crimson")
plt.plot([pred_pd["Delivery_Time"].min(), pred_pd["Delivery_Time"].max()],
         [pred_pd["Delivery_Time"].min(), pred_pd["Delivery_Time"].max()], 'k--', lw=2)
plt.title("Actual vs Predicted Delivery Time (Random Forest)", fontsize=14, fontweight='bold')
plt.xlabel("Actual Delivery Time (mins)")
plt.ylabel("Predicted Delivery Time (mins)")
plt.tight_layout()
plt.show()

print("\n✅ TẤT CẢ CÁC CELL ĐÃ HOÀN THÀNH VÀ CHẠY THÀNH CÔNG!")
